import { ProductType, CategoryType } from '@/types';

export const mockCategories: CategoryType[] = [
  {
    id: 'cat-1',
    name: 'Fruits & Vegetables',
    nameTamil: 'பழங்கள் & காய்கறிகள்',
    slug: 'fruits-vegetables',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&q=80&w=400',
    itemCount: 42,
  },
  {
    id: 'cat-2',
    name: 'Dairy & Eggs',
    nameTamil: 'பால் & முட்டை',
    slug: 'dairy-eggs',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&q=80&w=400',
    itemCount: 18,
  },
  {
    id: 'cat-3',
    name: 'Honey & Spices',
    nameTamil: 'தேன் & மசாலாக்கள்',
    slug: 'honey-spices',
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&q=80&w=400',
    itemCount: 24,
  },
  {
    id: 'cat-4',
    name: 'Grains & Flours',
    nameTamil: 'தானியங்கள் & மாவுகள்',
    slug: 'grains-flours',
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&q=80&w=400',
    itemCount: 15,
  },
  {
    id: 'cat-5',
    name: 'Beverages',
    nameTamil: 'பானங்கள்',
    slug: 'beverages',
    image: 'https://images.unsplash.com/photo-1523906630133-f6934a1ab26e?auto=format&fit=crop&q=80&w=400',
    itemCount: 12,
  },
];

export const mockProducts: ProductType[] = [
  {
    id: 'prod-1',
    name: 'Organic Red Tomatoes',
    nameTamil: 'இயற்கை தக்காளி',
    description: 'Freshly harvested organic vine-ripened red tomatoes. Sweet, juicy, and packed with vitamins.',
    descriptionTamil: 'புதிதாக அறுவடை செய்யப்பட்ட இயற்கை தக்காளி. இனிமையானது, சாறு நிறைந்தது மற்றும் வைட்டமின்கள் நிறைந்தது.',
    price: 60,
    images: ['https://images.unsplash.com/photo-1595855759920-86582396756a?auto=format&fit=crop&q=80&w=600'],
    category: 'Fruits & Vegetables',
    stock: 25,
    rating: 4.8,
    reviewsCount: 124,
    isOrganic: true,
    isLabTested: true,
    unit: '1kg',
  },
  {
    id: 'prod-2',
    name: 'Raw Mountain Honey',
    nameTamil: 'தூய காட்டுத் தேன்',
    description: '100% pure raw honey collected from wild hives in deep mountains. Unprocessed and unfiltered.',
    descriptionTamil: 'ஆழ்காட்டு மலை தேன்கூடுகளிலிருந்து சேகரிக்கப்பட்ட 100% தூய காட்டுத் தேன். பதப்படுத்தப்படாதது.',
    price: 350,
    images: ['https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&q=80&w=600'],
    category: 'Honey & Spices',
    stock: 12,
    rating: 4.9,
    reviewsCount: 85,
    isOrganic: true,
    isLabTested: true,
    unit: '500g',
  },
  {
    id: 'prod-3',
    name: 'Fresh Organic Spinach',
    nameTamil: 'பசலைக்கீரை',
    description: 'Crisp green baby spinach leaves grown using organic compost. Pre-washed and ready to consume.',
    descriptionTamil: 'இயற்கை உரம் கொண்டு வளர்க்கப்பட்ட புதிய பசலைக்கீரை. சுத்தம் செய்யப்படுக்கப்பட்டு சாப்பிட தயாராக உள்ளது.',
    price: 30,
    images: ['https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&q=80&w=600'],
    category: 'Fruits & Vegetables',
    stock: 30,
    rating: 4.6,
    reviewsCount: 42,
    isOrganic: true,
    isLabTested: false,
    unit: '250g',
  },
  {
    id: 'prod-4',
    name: 'Farm Fresh A2 Cow Milk',
    nameTamil: 'இயற்கை பசு பால்',
    description: 'Pure, organic A2 cow milk sourced from grass-fed native cows. Rich in protein and easy to digest.',
    descriptionTamil: 'புல்வெளியில் மேய்ந்த நாட்டுப் பசுக்களிடமிருந்து பெறப்பட்ட தூய, இயற்கை A2 பசு பால். எளிதில் ஜீரணமாகக்கூடியது.',
    price: 80,
    images: ['https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&q=80&w=600'],
    category: 'Dairy & Eggs',
    stock: 15,
    rating: 4.7,
    reviewsCount: 96,
    isOrganic: true,
    isLabTested: true,
    unit: '1L',
  },
  {
    id: 'prod-5',
    name: 'Stone-Ground Wheat Flour',
    nameTamil: 'நாட்டு கோதுமை மாவு',
    description: 'Traditionally stone-ground whole wheat flour. Retains all natural nutrients and dietary fibers.',
    descriptionTamil: 'பாரம்பரிய முறைப்படி கல் செக்கில் அரைக்கப்பட்ட கோதுமை மாவு. இயற்கை சத்துக்கள் மற்றும் நார்சத்துக்கள் கொண்டது.',
    price: 120,
    images: ['https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&q=80&w=600'],
    category: 'Grains & Flours',
    stock: 20,
    rating: 4.5,
    reviewsCount: 64,
    isOrganic: true,
    isLabTested: false,
    unit: '1kg',
  },
  {
    id: 'prod-6',
    name: 'Organic Brown Eggs',
    nameTamil: 'இயற்கை நாட்டு முட்டை',
    description: 'Free-range, organic brown chicken eggs. Nutrient-dense with rich orange yolks.',
    descriptionTamil: 'இயற்கையான முறையில் வளர்க்கப்பட்ட கோழி முட்டைகள். அதிக சத்துக்கள் மற்றும் அடர்ந்த மஞ்சள் கரு கொண்டது.',
    price: 90,
    images: ['https://images.unsplash.com/photo-1506976785307-8732e854ad03?auto=format&fit=crop&q=80&w=600'],
    category: 'Dairy & Eggs',
    stock: 8,
    rating: 4.8,
    reviewsCount: 110,
    isOrganic: true,
    isLabTested: true,
    unit: '6 items',
  },
  {
    id: 'prod-7',
    name: 'Cold-Pressed Coconut Oil',
    nameTamil: 'செக்கு தேங்காய் எண்ணெய்',
    description: 'Cold-pressed from sun-dried organic sulfur-free copra. Rich aroma and ideal for healthy cooking.',
    descriptionTamil: 'வெயிலில் காயவைக்கப்பட்ட இயற்கை தேங்காயிலிருந்து செக்கில் ஆட்டப்பட்ட எண்ணெய். சமையலுக்கு ஏற்றது.',
    price: 240,
    images: ['https://images.unsplash.com/photo-1622484211148-716598e04141?auto=format&fit=crop&q=80&w=600'],
    category: 'Honey & Spices',
    stock: 18,
    rating: 4.9,
    reviewsCount: 75,
    isOrganic: true,
    isLabTested: true,
    unit: '500ml',
  },
  {
    id: 'prod-8',
    name: 'Premium Green Tea Leaves',
    nameTamil: 'இயற்கை பச்சை தேநீர்',
    description: 'Hand-picked organic green tea leaves from Himalayan slopes. Rich in antioxidants and detox properties.',
    descriptionTamil: 'இமயமலைச் சரிவுகளில் இருந்து கைமுறையாக பறிக்கப்பட்ட தேயிலை இலைகள். ஆன்டி-ஆக்ஸிடன்ட்கள் நிறைந்தது.',
    price: 180,
    images: ['https://images.unsplash.com/photo-1523906630133-f6934a1ab26e?auto=format&fit=crop&q=80&w=600'],
    category: 'Beverages',
    stock: 0,
    rating: 4.4,
    reviewsCount: 39,
    isOrganic: true,
    isLabTested: false,
    unit: '250g',
  },
];

export const mockTestimonials = [
  {
    id: 'test-1',
    name: 'Priya Krishnan',
    location: 'Chennai',
    quote: 'The organic vegetables are so fresh, it reminds me of my grandmother’s farm. The taste is completely different from market vegetables!',
    quoteTamil: 'இயற்கை காய்கறிகள் மிகவும் புதியவை, இது எனது பாட்டியின் பண்ணையை நினைவூட்டுகிறது. சந்தை காயறிகளை விட இதன் சுவை முற்றிலும் மாறுபட்டது!',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=facearea&facepad=2&w=150&h=150&q=80',
  },
  {
    id: 'test-2',
    name: 'Rahul Sharma',
    location: 'Coimbatore',
    quote: 'Lab testing reports on every product give me absolute peace of mind. The raw mountain honey is stellar and incredibly pure.',
    quoteTamil: 'ஒவ்வொரு பொருளின் மீதான ஆய்வக சோதனை அறிக்கைகளும் எனக்கு முழுமையான மன அமைதியைத் தருகிறது. மலைத் தேன் மிக அற்புதமானது!',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=facearea&facepad=2&w=150&h=150&q=80',
  },
  {
    id: 'test-3',
    name: 'Anjali Mukund',
    location: 'Madurai',
    quote: 'Incredible delivery speed and fully biodegradable eco-friendly packaging. Highly recommend to anyone seeking authentic organic foods.',
    quoteTamil: 'நம்பமுடியாத விநியோக வேகம் மற்றும் முழுமையாக மட்கக்கூடிய பேக்கேஜிங். உண்மையான இயற்கை உணவுகளைத் தேடுவோருக்கு இதைப் பரிந்துரைக்கிறேன்.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=facearea&facepad=2&w=150&h=150&q=80',
  },
];

export const mockBlogs = [
  {
    id: 'blog-1',
    date: 'June 28, 2026',
    title: 'Understanding Organic Farming',
    titleTamil: 'இயற்கை விவசாயத்தைப் புரிந்துகொள்வது',
    excerpt: 'Discover how organic farming practices benefit your long-term health and protect the local environment.',
    excerptTamil: 'இயற்கை விவசாய முறைகள் உங்கள் ஆரோக்கியத்திற்கு எவ்வாறு நன்மை பயக்கும் மற்றும் சுற்றுச்சூழலைப் பாதுகாக்கும் என்பதை அறியுங்கள்.',
    image: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&q=80&w=600',
    slug: 'understanding-organic-farming',
  },
  {
    id: 'blog-2',
    date: 'June 25, 2026',
    title: 'The Truth About Raw Honey',
    titleTamil: 'தூய தேன் பற்றிய உண்மைகள்',
    excerpt: 'Is the honey on your table actually pure? Learn how to verify lab certifications and source checks.',
    excerptTamil: 'உங்கள் மேஜையில் உள்ள தேன் உண்மையில் தூய்மையானதா? ஆய்வகச் சான்றிதழ்கள் மற்றும் மூலச் சோதனைகளை எவ்வாறு சரிபார்ப்பது என அறியுங்கள்.',
    image: 'https://images.unsplash.com/photo-1471193945509-9ad0617afabf?auto=format&fit=crop&q=80&w=600',
    slug: 'truth-about-raw-honey',
  },
  {
    id: 'blog-3',
    date: 'June 20, 2026',
    title: 'Green Tea: A Daily Detox Guide',
    titleTamil: 'பச்சை தேநீர்: தினசரி நச்சுநீக்க வழிகாட்டி',
    excerpt: 'Unlock the health benefits of green tea and why brewing organic leaves makes a cellular difference.',
    excerptTamil: 'பச்சை தேநீரின் நன்மைகள் மற்றும் இயற்கை இலைகளை காய்ச்சுவது எவ்வாறு உடலுக்கு நல்லது என்பதை அறியுங்கள்.',
    image: 'https://images.unsplash.com/photo-1563822249548-9a72b6353cd1?auto=format&fit=crop&q=80&w=600',
    slug: 'green-tea-detox-guide',
  },
];
